### ISSUE TITLE
weird text block being sent

### ISSUE THREAD

**Issue by StandingPadAnimations** [Gorialis/jishaku#107] opened 2021-06-04 00:14 UTC
## Summary

So when I use >jsk py *bot sends something*, it has a weird text block after it executes: 
![Screenshot_20210603-190822_Discord](https://user-images.githubusercontent.comLoad 58058/120727134-63508e80-c49f-11eb-8376-52526d987b06.jpg)

## Reproduction steps
Load jsk as a cog and use the python evaluate command to make the bot send something

When evaluating anything that involves the bot sending something

## Expected results

For it to send the results without the text block

## Actual results

Sends the text box(though it evaluates fine)

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information
Raspberry Pi 4
Raspbian Buster 
Python 3.9.1

Discord.py: 1.7.1
Jishaku: latest(just installed today)

**Comment by StandingPadAnimations** [comment] 2021-06-04 00:28
Here's what I mean:
![Screenshot_20210603-192701_Discord](https://user-images.githubusercontent.com/75058058/120728100-c80ce880-c4a1-11eb-8201-14ef26e71af3.jpg)

**Comment by Gorialis** [comment] 2021-06-04 00:33
Duplicate of #106 and #63

**Closed by Gorialis** 2021-06-04 00:33 UTC
