### ISSUE TITLE
AttributeError: 'PaginatorInterface' object has no attribute '_View__timeout_task'

### ISSUE THREAD

**Issue by jottew** [Gorialis/jishaku#171] opened 2022-05-01 20:45 UTC
## Summary

Whenever I try to run jishaku shell I get that error, I have had this for a while now and updating discord.py and jishaku didn’t help

## Reproduction steps

Run a bot with python 3.9.12, discord.py 2.0.0a4084+g1e4908b and 2.3.2a391+g046189f and try to run any code with jishaku shell

## Expected results

Normally executes the code and sends the result

## Actual Result

The bot DM's me 

`
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/jishaku/features/shell.py", line 46, in jsk_shell
    interface = PaginatorInterface(ctx.bot, paginator, owner=ctx.author)
  File "/usr/local/lib/python3.9/dist-packages/jishaku/shim/paginator_200.py", line 73, in __init__
    self.timeout = kwargs.pop('timeout', 7200)
  File "/usr/local/lib/python3.9/dist-packages/discord/ui/view.py", line 247, in timeout
    if self.__timeout_task is not None:
AttributeError: 'PaginatorInterface' object has no attribute '_View__timeout_task'`

## Checklist

- [ ] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information
Discord.py version 2.0.0a4084+g1e4908b and jishaku version 2.3.2a391+g046189f

**Comment by Gorialis** [comment] 2022-05-01 21:00
This is a duplicate of #160 and it is already fixed. Update jishaku as per the repo instructions.

**Closed by Gorialis** 2022-05-01 21:00 UTC
